stages:
  - build

.docker:
  image: docker:18.09.7-dind
  services:
    - docker:dind
  before_script:
    - apk update
    - apk upgrade
    - apk add --no-cache python python-dev py-pip build-base curl
    - pip install docker-compose==1.24.0
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  

build:
  stage: build
  extends: .docker
  script: 
    - echo "Building the app"
    - docker-compose -f docker-compose-acdh.yml build
    - docker push docker.gitlab.gwdg.de/sshoc/sshoc-marketplace-backend:latest
  only:
  - develop

   
