stages:
  - test
  - build

test:
  stage: test
  script: echo "Running tests"

.docker:
  image: docker:19.03.0-dind
  services:
    - docker:dind
  before_script:
    - apk update
    - apk upgrade
    - apk add python python-dev py-pip build-base
    - curl -L https://github.com/docker/compose/releases/download/1.8.0/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
    - chmod +x /usr/local/bin/docker-compose
    - pip install docker-compose
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  

build:
  stage: build
  extends: .docker
  script: 
    - echo "Building the app"
    - docker-compose -f docker-compose-acdh.yml build
    - docker push docker.gitlab.gwdg.de/sshoc/sshoc-marketplace-backend:latest
  only:
  - develop
   
