stages:
  - build

.docker:
  image: qmarketing/dind-docker-compose:18.09.5
  services:
    - docker:dind
  before_script:
    - export DOCKER_HOST=127.0.0.1:2375
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  

build:
  stage: build
  extends: .docker
  script: 
    - echo "Building the app"
    - docker-compose -f docker-compose-acdh.yml build
    - docker push docker.gitlab.gwdg.de/sshoc/sshoc-marketplace-backend:latest
  only:
  - develop

   
