stages:
  - test
  - build

test:
  stage: test
  script: echo "Running tests"

.docker:
  image: docker:19.03.0-dind
  services:
    - docker:dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  

build:
  stage: build
  extends: .docker
  script: 
    - echo "Building the app"
    - docker-compose -f docker-compose-acdh.yml build
    - docker push docker.gitlab.gwdg.de/sshoc/sshoc-marketplace-backend:latest
  only:
  - develop
   
