stages:
  - test
  - build

test:
  stage: test
  script: echo "Running tests"

build:
  stage: build
  script: 
    - echo "Building the app"
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker-compose -f docker-compose-acdh.yml build
    - docker push docker.gitlab.gwdg.de/sshoc/sshoc-marketplace-backend:latest
  only:
  - develop
   
