stages:
  - build

.docker:
  image:
    name: docker:19.03-dind
  services:
    - docker:dind
  variables:
        FF_NETWORK_PER_BUILD: 1
        DOCKER_TLS_CERTDIR: ""    
        DOCKER_HOST: tcp://docker:2378
  before_script:
     - apk add --no-cache py-pip
     - pip install docker-compose==1.23.0
     - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY


build:
  stage: build
  tags:
    - sshoc-acdh-runner
  extends: .docker
  script: 
    - echo "Building the app (develop)"
    - docker-compose -f docker-compose-acdh-develop.yml build 
    - docker push docker.gitlab.gwdg.de/sshoc/sshoc-marketplace-backend/api:latest
    - docker push docker.gitlab.gwdg.de/sshoc/sshoc-marketplace-backend/solr:latest
  only:
  - develop

build-prod:
  stage: build
  tags:
    - sshoc-acdh-runner
  extends: .docker
  script:
    - echo "Building the app (prod)"
    - docker-compose -f docker-compose-acdh-prod.yml build
    - docker push docker.gitlab.gwdg.de/sshoc/sshoc-marketplace-backend/api-prod:latest
    - docker push docker.gitlab.gwdg.de/sshoc/sshoc-marketplace-backend/solr-prod:latest
  only:
    - master

