stages:
  - build

variables:
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: tcp://localhost:2375  

.docker:
  image:
    name: docker:18.09.7-dind
  services:
    - docker:dind
  before_script:
     - apk add --no-cache py-pip curl
     - pip install docker-compose==1.23.0
     - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  

build:
  stage: build
  extends: .docker
  script: 
    - echo "Building the app"
    - docker-compose -f docker-compose-acdh.yml build
    - docker push docker.gitlab.gwdg.de/sshoc/sshoc-marketplace-backend:latest
  only:
  - develop

   
