stages:
  - build

.docker:
  image:
    name: docker/compose:1.25.0
    entrypoint: ["/bin/sh", "-c"]
  variables:
    DOCKER_HOST: tcp://docker:2375 
  services:
    - docker:dind
  script:
    - docker version
    - docker-compose version
  before_script:
     - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  

build:
  stage: build
  extends: .docker
  script: 
    - echo "Building the app"
    - docker-compose -f docker-compose-acdh.yml build
    - docker push docker.gitlab.gwdg.de/sshoc/sshoc-marketplace-backend:latest
  only:
  - develop

   
