version: '3'
services:
  marketplacespring:
    container_name: marketplacespring
    build:
      context: ./
      dockerfile: Dockerfile
    working_dir: /opt/marketplace
    environment:
      SPRING_DATA_SOURCE_URL: ${SPRING_DATA_SOURCE_URL}
      SPRING_DATA_SOURCE_USER: ${POSTGRES_USER}
      SPRING_DATA_SOURCE_PWD: ${POSTGRES_PASSWORD}
    ports:
      - 8080
    depends_on:
      - psql

  psql:
    container_name: psql
    image: postgres:9.6
    volumes:
      - psql-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432
    restart: always
volumes:
  psql-data: