version: "2"

services:
  psql:
    image: postgres:9.6
    ports:
      - 5432:5432
    volumes:
      - psql-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: marketplace_db
      POSTGRES_USER: marketplace
      POSTGRES_PASSWORD: marketplace

  solr:
    build: etc/solr
    ports:
      - 8983:8983
    volumes:
      - solr-data:/var/solr

volumes:
  psql-data:
  solr-data:

