version: "3"

services:
  marketplace:
    build:
      context: .
      dockerfile: container/Dockerfile
    image: docker.gitlab.gwdg.de/sshoc/sshoc-marketplace-backend/kubernetes-test
    ports:
      - 5000:5000
      - 9990:9990
    depends_on:
      - psql
      - solr
    environment:
      APPLICATION_PROFILE: dev
      aai_base_uri: https://aai.eosc-portal.eu/oidc
      egi_id: ${egi_id}
      egi_secret: ${egi_secret}
      token_secret: ${token_secret}
      recaptcha_site_key: ${recaptcha_site_key}
      recaptcha_secret_key: ${recaptcha_secret_key}
      marketplace_log_dir: /tmp
      marketplace_media_dir: /var/sshoc/media
    volumes:
      - media-data:/var/sshoc/media

  psql:
    image: bitnami/postgresql:9.6.16
    ports:
      - 5432:5432
    volumes:
      - psql-data:/bitnami/postgresql
    environment:
      POSTGRESQL_DATABASE: marketplace_db
      POSTGRESQL_USERNAME: user
      POSTGRESQL_PASSWORD: testing-password

  solr:
    build: etc/solr
    image: docker.gitlab.gwdg.de/sshoc/sshoc-marketplace-backend/solr:latest
    ports:
      - 8983:8983
    volumes:
      - solr-data:/var/solr

volumes:
  psql-data:
  solr-data:
  media-data:
