version: "2"
services:
  marketplace-prod:
    build:
      context: .
      dockerfile: Dockerfile-acdh-ch
      args:
        - GID=1031
        - UID=1031
    image: docker.gitlab.gwdg.de/sshoc/sshoc-marketplace-backend/api-prod:latest
    container_name: sshoc-marketplace-backend-api-prod
    ports:
      - 8080:8080
    depends_on:
      - psql-prod
      - solr-prod
    environment:
      APPLICATION_PROFILE: prod
      POSTGRES_DB: marketplace_db
      POSTGRES_USER: marketplace
      POSTGRES_PASSWORD: marketplace
      POSTGRES_HOST: psql-prod
      POSTGRES_PORT: 5432
      SOLR_HOST: solr-prod
      SOLR_PORT: 8983
      egi_id: ${egi_id}
      egi_secret: ${egi_secret}
      token_secret: ${token_secret}
      recaptcha_site_key: ${recaptcha_site_key}
      recaptcha_secret_key: ${recaptcha_secret_key}
      marketplace_log_dir: /log
    labels:
      - traefik.backend=marketplace-api-prod
      - traefik.frontend.rule=Host:marketplace-api-prod.sisyphos.arz.oeaw.ac.at,sshoc-marketplace-api.acdh.oeaw.ac.at,marketplace-api.sshoc.eu,marketplace-api.sshopencloud.eu
      - traefik.docker.network=web
      - traefik.port=8080
      - ID=17458
    networks:
      - backend
      - web
    volumes:
      - app-log:/log

  psql-prod:
    image: postgres:9.6
    container_name: sshoc-marketplace-backend-postgres-prod
    ports:
      - 5432:5432
    volumes:
      - psql-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: marketplace_db
      POSTGRES_USER: marketplace
      POSTGRES_PASSWORD: marketplace
      POSTGRES_HOST: psql-prod
    labels:
      - ID=18663
    networks:
      - backend
  solr-prod:
    build: etc/solr
    image: docker.gitlab.gwdg.de/sshoc/sshoc-marketplace-backend/solr-prod:latest
    container_name: sshoc-marketplace-backend-solr-prod
    ports:
      - 8983:8983
    volumes:
      - solr-data:/var/solr
    labels:
      - traefik.backend=solr-prod
      - traefik.frontend.rule=Host:marketplace-solr-prod.sisyphos.arz.oeaw.ac.at
      - traefik.docker.network=web
      - traefik.port=8983
      - ID=18664
    networks:
      - backend
      - web
networks:
  backend:
    driver: bridge
  web:
    external:
      name: web
volumes:
  psql-data:
    driver: local
    driver_opts:
      type: "none"
      device: "/home/sshocmarketplacecuration/shares/psql-data"
      o: "bind"
  solr-data:
    driver: local
    driver_opts:
      type: "none"
      device: "/home/sshocmarketplacecuration/shares/solr-data"
      o: "bind"
  app-log:
    driver: local
    driver_opts:
      type: "none"
      device: "/home/sshocmp/shares/app-log"
      o: "bind"
