apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ print (.Values.pvc.namePrefix) ( include "fullname" . ) "-app-log"| quote }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
