apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ print ( include "fullname" . ) "-postgres"| quote }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
