apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ print (.Values.pvc.namePrefix) ( include "fullname" . ) "-media-data"| quote }}
spec:
  accessModes:
  {{- range .Values.pvc.accessModes}}
    - {{ toYaml . }}
  {{- end }}
  resources:
    requests:
      storage: 1Gi