apiVersion: v1
kind: Secret
type: Opaque
metadata:
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
  name: {{ template "fullname" . }}-postgres
data:
  POSTGRES_DB: {{ .Values.postgres.dbname | default "marketplace" | b64enc }}
  POSTGRES_HOST: {{ .Values.postgres.host | default ( print ( include "fullname" . ) "-postgres" ) | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password | default (randAlphaNum 16) | b64enc }}
  POSTGRES_PORT: {{ .Values.postgres.port | default "5432" | b64enc }}
  POSTGRES_USER: {{ .Values.postgres.user | default (printf "%s" (include "fullname" .)) | b64enc }}