server:
    port: 8080

spring:
    datasource:
        driver-class-name: "org.postgresql.Driver"
        url: "jdbc:postgresql://localhost:5432/marketplace_db"
        username: marketplace
        password: marketplace
        hikari:
            connection-timeout: 60000
            maximum-pool-size: 5
    jpa:
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate: 
                jdbc:
                    lob: 
                        non_contextual_creation: true
    data:
        solr:
            host: "http://localhost:8983/solr"

    mvc.:
        throw-exception-if-no-handler-found: true

springdoc:
    version: '@api.version@'
    api-docs:
        enabled: true
        path: /v3/api-docs

marketplace:
    pagination:
        default-perpage: 20
        maximal-perpage: 100
