spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:"jdbc:postgresql://localhost:5433/marketplace_db}
  jpa:
    show-sql: true
  data:
    solr:
      host: ${SPRING_DATA_SOLR_HOST:http://localhost:8984/solr}

    liquibase:
        contexts: test

marketplace:
    media:
        files:
            path: /tmp/${random.value}/sshoc/media
