spring:
    datasource:
        url: "jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}"
        username: ${POSTGRES_USER}
        password: ${POSTGRES_PASSWORD}
    data:
        solr:
            host: "http://${SOLR_HOST}:${SOLR_PORT}/solr"

    liquibase:
        contexts: prod

handle:
  base-url: ${HANDLE_BASE_URL}
  app-handle-value: ${HANDLE_APP_VALUE}
  user-id-handle: ${HANDLE_USER_ID}
  user-id-index: ${HANDLE_USER_ID_INDEX}
  key-location: ${HANDLE_KEY_LOCATION}
