spring:
    datasource:
        url: "jdbc:postgresql://localhost:5433/marketplace_db"
    jpa:
        show-sql: true
    data:
        solr:
            host: "http://localhost:8984/solr"

    liquibase:
        contexts: test

marketplace:
    media:
        files:
            path: /tmp/${random.value}/sshoc/media
