spring:
    datasource:
        url: "jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}"
        username: ${POSTGRES_USER}
        password: ${POSTGRES_PASSWORD}
    data:
        solr:
            host: "http://${SOLR_HOST}:${SOLR_PORT}/solr"

    liquibase:
        contexts: prod
