server:
    port: 8080
    forward-headers-strategy: native
    tomcat:
        internal-proxies: .*


spring:
    datasource:
        driver-class-name: "org.postgresql.Driver"
        url: "jdbc:postgresql://localhost:5432/marketplace_db"
        username: marketplace
        password: marketplace

        hikari:
            initialization-fail-timeout: 10000
            connection-timeout: 60000
            maximum-pool-size: 5
    jpa:
        hibernate:
            ddl-auto: validate

        show-sql: false
        open-in-view: false
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQL9Dialect
                jdbc:
                    lob: 
                        non_contextual_creation: true

    jackson:
        serialization:
            fail-on-empty-beans: false
    data:
        solr:
            host: "http://localhost:8983/solr"

    mvc:
        throw-exception-if-no-handler-found: true

    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 10MB

    security:
        oauth2:
            client:
                registration:
                    eosc:
                        client-id: ${egi_client_id:deafult-egi-id}
                        client-secret: ${egi_secret:default-egi-secret}
                        authorization-grant-type: authorization_code
                        scope:
                            - openid
                            - profile
                            - email
                            - eduperson_scoped_affiliation
                            - eduperson_entitlement
                        redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
                        client-name: EOSC
                provider:
                    eosc:
                        token-uri: https://aai-dev.egi.eu/oidc/token
                        authorization-uri: https://aai-dev.egi.eu/oidc/authorize
                        user-info-uri: https://aai-dev.egi.eu/oidc/userinfo
                        jwk-set-uri: https://aai-dev.egi.eu/oidc/jwk
                        user-name-attribute: sub

    profiles:
        active: ${APPLICATION_PROFILE:}

springdoc:
    version: '@api.version@'
    api-docs:
        enabled: true
        path: /v3/api-docs

marketplace:
    cors:
        max-age-sec: 3600
    pagination:
        default-perpage: 20
        maximal-perpage: 100
    security:
        auth:
            jwt-token-secret: ${token_secret:default-token-secret}
            jwt-token-expiration-msec: 86400000
        oauth:
            implicit-grant-token-expiration-msec: 30000
    logging:
        path: ${marketplace_log_dir:/tmp}

